server:
  port: 8787
spring:
    datasource:
        name: test
        url: jdbc:mysql://120.78.189.119:3306/blog?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
    mvc:
      static-path-pattern: /resources/**
mybatis:
    typeAliasesPackage: com.xdd.entity
    mapperLocations: classpath:mapper/*.xml
    configLocation: classpath:mybatis-config.xml
web:
    upload: D:/image/